language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
script:
  - gulp --prod
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
